### ISSUE TITLE
Integration init issue after upgrade of HASS Core

### ISSUE THREAD

**Issue by andreifinski** [Southern-Company-HA/southern-company-hacs#38]
Upgraded to the new HA core Supervisor 2023.06.1 and cannot start the integration afterwards

## Version of the custom_component

0.1.9

## Describe the bug

Cannot load the integration after init

## Debug log

`Unexpected error fetching Southern Company Hacs data: 'dict' object has no attribute 'discard'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/southern_company_hacs/coordinator.py", line 62, in _async_update_data
    await self._insert_statistics()
  File "/config/custom_components/southern_company_hacs/coordinator.py", line 78, in _insert_statistics
    last_stats = await get_instance(self.hass).async_add_executor_job(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/recorder/statistics.py", line 1806, in get_last_statistics
    return _get_last_statistics(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/recorder/statistics.py", line 1770, in _get_last_statistics
    metadata_ids = _extract_metadata_and_discard_impossible_columns(metadata, types)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/recorder/statistics.py", line 1526, in _extract_metadata_and_discard_impossible_columns
    types.discard("mean")
    ^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'discard'`

**Comment by Lash-L** [comment]
Are you sure you are on version 0.1.9, I believe I fixed the exact error you are facing.

**Comment by andreifinski** [comment]
oh, just killed the old one completely and redownloaded - all good, my bad!
